import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { UserProvider } from "@/contexts/UserContext";
import Navbar from "@/components/Layout/Navbar";
import ChatBox from "@/components/ChatAssistant/ChatBox";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
      >
        <UserProvider>
          <TooltipProvider>
            <Toaster />
            <Sonner />
            <Navbar />
            <ChatBox />
            {children}
          </TooltipProvider>
        </UserProvider>
      </body>
    </html>
  );
}
